INSERT INTO skills (name_skill, year_skill, last_used_skill,last_check_skill,checked_by_skill) VALUES
	('Primary skill / .Net', 2, 2015, 12/15/2015,'Ivanov Ivan'),
	('Primary skill / ActionScript', 1, 2003, 01/11/2003,'Ivanov Ivan'),
	('Primary skill / AEM', 3, 2002, 18/12/2002,'Ivanov Ivan');
	
INSERT INTO skills (name_skill, year_skill, last_used_skill) VALUES
	('Domain / Agriculture / Dairy', 5, 2006),
	('Domain / Agriculture / Farming', 5, 2015),
	('Industry Vertical / Emerging Verticals', 3, 2015),
	('Industry Vertical / Financial Services', 5, 2006),
	('Industry Vertical / Life Sciences & Healthcare', 3, 2015),
	('Language / Chinese / Speaking', 4, 2011),
	('Language / Chinese / Writing', 2, 2015),
	('Language / English / Speaking', 1, 2001),
	('Willing to go to business trip', 2, 2000),
	('Willing to relocate to Europe', 3, 2011),
	('Willing to relocate to USA', 2, 2008),
	('Architecture / Cloud', 2, 2008),
	('Augmented Reality (AR)', 2, 2000),
	('Augmented Reality (AR)', 2, 2015),
	('Mobile / Android platform', 3, 2004),
	('Mobile / Blackberry platform', 5, 2012),
	('Mobile / Cross platform development / Infragistics', 4, 2011),
	('Programming Languages / ActionScript', 5, 2002),
	('Programming Languages / C', 2, 2001),
	('Programming Languages / C#', 5, 2003),
	('Architecture / Business logic / Analytics', 3, 2005),
	('Architecture / Business logic / Booking engine', 4, 2006),
	('Architecture / Business logic / Business Process Management', 5, 2012),
	('Methodologies / Estimation', 2, 2007),
	('Methodologies / IDEF0', 2, 2013),
	('Methodologies / IDEF3', 2, 2005),
	('Software Testing / Automation Testing / Back-end', 2, 2004),
	('Software Testing / Automation Testing / Mobile', 1, 2006),
	('Software Testing / Automation Testing / TV Consoles', 2, 2002),
	('Application Server / ATG Dynamo', 5, 2016),
	('Application Server / Azure Service Fabric', 5, 2008),
	('Application Server / GlassFish', 1, 2002),
	('Design / Illustration work using graphics tablets', 4, 2002),
	('Design Tools / 3Ds Max', 1, 2011),
	('Design Tools / Adobe Acrobat', 2, 2006),
	('eCommerce / Elasti? Path', 2, 2009),
	('Background check', 3, 2001),
	('Dollar card (Alfa Bank)', 1, 2001),
	('Other / Student', 4, 2004),
	('Expert skill / Assessment Interview', 3, 2017),
	('Expert skill / Communities / Leading', 4, 2000),
	('Expert skill / Communities / Participation', 2, 2010);
INSERT INTO skill_types (name_skill_type) VALUES
	('Industry / Domain Knowledge'),
	('Industry / Domain Knowledge'),
	('Industry vertical'),
	('Industry vertical'),
	('Industry vertical'),
	('Languages'),
	('Languages'),
	('Languages'),
	('Other'),
	('Other'),
	('Other'),
	('Technical / Development'),
	('Technical / Development'),
	('Technical / Development'),
	('Technical / Mobile'),
	('Technical / Mobile'),
	('Technical / Mobile'),
	('Technical / Programming Languages and Platforms'),
	('Technical / Programming Languages and Platforms'),
	('Technical / Programming Languages and Platforms'),
	('Technical / Project Architecture'),
	('Technical / Project Architecture'),
	('Technical / Project Architecture'),
	('Technical / Project Management'),
	('Technical / Project Management'),
	('Technical / Project Management'),
	('Technical / QA & QC'),
	('Technical / QA & QC'),
	('Technical / QA & QC'),
	('Technical / System Administration & DevOps'),
	('Technical / System Administration & DevOps'),
	('Technical / System Administration & DevOps'),
	('Technical / Visual Design'),
	('Technical / Visual Design'),
	('Technical / Visual Design'),
	('Technical / Development'),
	('Primary'),
	('Primary'),
	('Primary'),
	('Other'),
	('Other'),
	('Other'),
	('Expert'),
	('Expert'),
	('Expert');
INSERT INTO skill_statuses (name_skill_status) VALUES
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Announced'),
	('Proposed for including'),
	('Unannounced'),
	('Unannounced'),
	('Unannounced'),
	('Unannounced'),
	('Unannounced'),
	('Unannounced'),
	('Unannounced'),
	('Unannounced'),
	('Unannounced');